name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source 🛎️
      uses: actions/checkout@v7

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: maven

    - name: Build with Maven 🔧
      run: mvn -B package --file pom.xml

    - name: Archive artifacts
      uses: actions/upload-artifact@v7
      with:
        name: Artifacts
        path: |
          ./target/*.jar
          ./target/*.obr

    - name: Release using Github CLI
      run: gh release create ${GITHUB_REF##*/} ./target/*.jar ./target/*.obr -t "Release ${GITHUB_REF##*/}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy artifacts
      run: |
        mkdir artifacts
        cp target/*.jar artifacts/
        cp target/*.obr artifacts/
        rm artifacts/*-tests.jar
        ls artifacts

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: artifacts
        clean: false
        target-folder: ${{ github.ref_name }}
        commit-message: Releasing tag/branch ${{ github.ref_name }}
